const tlp = require('./html.ejs');
const data = [{
    img: '../../assets/img/item.jpg',
    title: '东瀛散步｜是谁打造了日本这三间最有人气的Guest House？',
    text: '当原田置发出规律的哒哒哒的木头声响',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '7898',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '在最感性的季节里，我们准备了一份书单和影单，陪你窝在沙发里',
    text: '秋天的每一次造访，都延续着其特有的气息：淅淅沥沥的秋雨',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '123123',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '东瀛散步｜是谁打造了日本这三间最有人气的Guest House？',
    text: '当原田置发出规律的哒哒哒的木头声响',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '7898',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '在最感性的季节里，我们准备了一份书单和影单，陪你窝在沙发里',
    text: '秋天的每一次造访，都延续着其特有的气息：淅淅沥沥的秋雨',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '123123',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '东瀛散步｜是谁打造了日本这三间最有人气的Guest House？',
    text: '当原田置发出规律的哒哒哒的木头声响',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '7898',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '在最感性的季节里，我们准备了一份书单和影单，陪你窝在沙发里',
    text: '秋天的每一次造访，都延续着其特有的气息：淅淅沥沥的秋雨',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '123123',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '东瀛散步｜是谁打造了日本这三间最有人气的Guest House？',
    text: '当原田置发出规律的哒哒哒的木头声响',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '7898',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '在最感性的季节里，我们准备了一份书单和影单，陪你窝在沙发里',
    text: '秋天的每一次造访，都延续着其特有的气息：淅淅沥沥的秋雨',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '123123',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '东瀛散步｜是谁打造了日本这三间最有人气的Guest House？',
    text: '当原田置发出规律的哒哒哒的木头声响',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '7898',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '在最感性的季节里，我们准备了一份书单和影单，陪你窝在沙发里',
    text: '秋天的每一次造访，都延续着其特有的气息：淅淅沥沥的秋雨',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '123123',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '东瀛散步｜是谁打造了日本这三间最有人气的Guest House？',
    text: '当原田置发出规律的哒哒哒的木头声响',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '7898',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '在最感性的季节里，我们准备了一份书单和影单，陪你窝在沙发里',
    text: '秋天的每一次造访，都延续着其特有的气息：淅淅沥沥的秋雨',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '123123',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '东瀛散步｜是谁打造了日本这三间最有人气的Guest House？',
    text: '当原田置发出规律的哒哒哒的木头声响',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '7898',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '在最感性的季节里，我们准备了一份书单和影单，陪你窝在沙发里',
    text: '秋天的每一次造访，都延续着其特有的气息：淅淅沥沥的秋雨',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '123123',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '东瀛散步｜是谁打造了日本这三间最有人气的Guest House？',
    text: '当原田置发出规律的哒哒哒的木头声响',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '7898',
    tag: 'Angularjs',
},{
    img: '../../assets/img/item.jpg',
    title: '在最感性的季节里，我们准备了一份书单和影单，陪你窝在沙发里',
    text: '秋天的每一次造访，都延续着其特有的气息：淅淅沥沥的秋雨',
    time: 'MAY 5TH 2016',
    author: '杨盼',
    pv: '123123',
    tag: 'Angularjs',
}];
module.exports = function tlpfun(){
    return tlp({ data });
};